env:
  global:
    # get the latest code from master
    # - SENECA_VER=
    # to clone a specific tagged version set the version like the following:
    - SENECA_VER=#v1.3.0

  matrix:
    # plugins to test
    - TEST_SUITE=senecajs/seneca-postgres-store
    - TEST_SUITE=Concorda/seneca-auth
    - TEST_SUITE=rjrodger/seneca-balance-client
    - TEST_SUITE=senecajs/seneca-basic
    - TEST_SUITE=senecajs/seneca-cache
    - TEST_SUITE=senecajs/seneca-entity
    - TEST_SUITE=rjrodger/seneca-error-test
    - TEST_SUITE=rjrodger/seneca-jsonfile-store
    - TEST_SUITE=senecajs/seneca-level-store
    - TEST_SUITE=senecajs/seneca-mem-store
    - TEST_SUITE=rjrodger/seneca-mesh
    - TEST_SUITE=senecajs/seneca-mysql-store
    - TEST_SUITE=senecajs/seneca-quartz-scheduler
    - TEST_SUITE=senecajs/seneca-redis-cache
    - TEST_SUITE=senecajs/seneca-repl
    - TEST_SUITE=senecajs/seneca-store-test
    - TEST_SUITE=senecajs/seneca-transport
    - TEST_SUITE=rjrodger/seneca-transport-test
    - TEST_SUITE=senecajs/seneca-user
    - TEST_SUITE=senecajs/seneca-web
    - TEST_SUITE=senecajs/seneca-redis-store
    - TEST_SUITE=senecajs/seneca-sqlite-store
    - TEST_SUITE=senecajs/seneca-mongo-store
    - TEST_SUITE=senecajs/seneca

before_script:
  - git clone https://github.com/$TEST_SUITE
  - if [ $TEST_SUITE = 'seneca-postgres-store' ]; then psql -U postgres -f seneca-postgres-store/docker/dbschema.sql ; fi
  - if [ $TEST_SUITE = 'seneca-mysql-store' ]; then mysql -h localhost -u root --password="" seneca-mysql-store/docker/schema.sql ; fi
  - cd $(basename $TEST_SUITE)
  - npm i
  - npm install https://github.com/senecajs/seneca$SENECA_VER

language: node_js
sudo: false

cache:
  directories:
  - node_modules

node_js:
  - '4'

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql
